export const rewards = [
  {
    image: require('../assets/Images/google.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/Utube.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/PB.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/hawkings.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/PB.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/flipkart.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/PB.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
  {
    image: require('../assets/Images/hawkings.png'),
    mss1: 'Child Education',
    mss2: '"GOOGLE254"',
    mss3: 'Expire in',
    mss4: '12:30:56',
    mss5: '120 Points',
  },
];
